# Generated by Django 2.0 on 2017-12-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invetory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stocked', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
