# Generated by Django 2.0 on 2017-12-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('gd', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('date', models.DateField()),
                ('home', models.IntegerField()),
                ('away', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('team_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
    ]
